### ISSUE TITLE
Price at which orders get matched are not correct

### ISSUE THREAD

**Issue by hkirat** [hkirat/trade-assignment#2]
Issue exists in this line - https://github.com/hkirat/trade-assignment/blob/master/src/index.ts#L149
Probably should be matched based on the bid/ask price vs the user provided price

**Comment by khushminder270** [comment]
@hkirat  Please assign me this issue.

**Comment by khushminder270** [comment]
@hkirat  pending PR #3 for this issue

**Comment by DiproPramanick1999** [comment]
Fix related to price.[Issue#2 #8](https://github.com/hkirat/trade-assignment/pull/8)
